#!/bin/bash

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Autor: Brian Mayo
# Contact:     brianmay.dev@gmail.com
# Created:     9/9/2014
# Licence:     GNU GPL v3
# Version: 	   1.0.0
# Requeriments:	zip
#				node-webkit
# Description: This script allows to execute Node Webkit based apps easily zipping your app and moving it to apps folder in node webkit folder.
# Usage: For using this script you must set up the variable "nw_path" with the full path to node webkit folder.
#		 The node webkit folder must not contains white spaces.
#		 Put this script in the root folder of the app and execute it (same folder as package.json) or make a link in /bin folder.
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

nw_path="/path/to/node-webkit" # set up this. Ex /home/node-webkit
nw_apps_path="$nw_path/apps"

if [[ ! -f "$PWD/package.json" ]]; then
	echo "No package.json file founded. Execution failed."
fi

old=$IFS
IFS=', '
exclude=()
while getopts x:c flag; do
  case $flag in
    x) 
		set +f
		GLOBIGNORE=*
		exclude=( $OPTARG );;
	c) 
		if [ "$(ls -A $nw_apps_path)" ]; then
			rm -r $nw_apps_path/*
		fi
		echo "Node Webkit apps deleted."
		exit
		;;
    *) break ;;
  esac
done

IFS=$'\n'

if [[ ! -d "$nw_apps_path" ]]; then
	mkdir "$nw_apps_path" # nw apps folder
fi

app_name="${PWD##*/}.nw"
app_nw="$nw_apps_path/$app_name"

z="zip -q -r $app_name . "
if [[ ! ${#exclude[@]} -eq 0 ]]; then
	z+="-x"
	for x in "${exclude[@]}"
	do
	  z+=" \"$x\""
	done
fi

bash -c "$z"
if [[ -f "$app_nw" ]]; then
	rm "$app_nw"
fi

mv "$app_name" "$app_nw"
cd "$nw_path"
if [[ ! -f "nw" ]]; then
	echo "nw binary not founded. Execution failed."
	exit 1
fi

./nw "apps/$app_name"

IFS=$old

exit