#!/bin/bash

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Autor: Brian Mayo
# Version: 1.0.0
# Description: This script allows to execute Node Webkit based apps easily zipping your app and moving it to apps folder in node webkit folder.
# Usage: For using this script you must set up the variable "nw_path" with the full path to node webkit folder.
#		 The node webkit folder must not contains white spaces.
#		 Put this script in the root folder of the app and execute it (same folder as package.json) or make a link in /bin folder.
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

if [[ ! -f "$PWD/package.json" ]]; then
	echo "No package.json file founded. Execution failed."
fi

old=$IFS
IFS=', '
set +f
GLOBIGNORE=*

while getopts x: flag; do
  case $flag in
    x) exclude=( $OPTARG );;
    *) break ;;
  esac
done

IFS=$'\n'

nw_path="/home/brian/Programs/nw" # set up this. Ex /home/node-webkit
nw_apps_path="$nw_path/apps"

if [[ ! -d "$nw_apps_path" ]]; then
	mkdir "$nw_apps_path" # nw apps folder
fi

app_name="${PWD##*/}.nw"
app_nw="$nw_apps_path/$app_name"

zip -q -r "$app_name" . -x "${exclude[@]}"

if [[ -f "$app_nw" ]]; then
	rm "$app_nw"
fi

mv "$app_name" "$app_nw"
cd "$nw_path"
if [[ ! -f "nw" ]]; then
	echo "nw binary not founded. Execution failed."
	exit 1
fi

./nw "apps/$app_name"

IFS=$old

exit